### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by ejkarne** [marc0tjevp/United-GTK#1]
I just came across this repo after looking into the United theme and this looks so much better than the generic material design theme the original has become. Are you still planning to maintain this?

**Comment by marc0tjevp** [comment]
I sure am planning on maintaining this, but I don't have enough knowledge at this very moment to do so. Feel free to contribute. I will resume this project in the near future.

**Comment by ejkarne** [comment]
If you're interested, the original theme currently has an open issue contemplating moving the design more towards Unity 8 and/or the original concept. It might help if you share your opinion there.

If the theme does end up moving towards the original concept then it would be easier to fork and cherry pick changes from the original concept to add back. The advantage of doing that instead of maintaining this fork is that a lot of the changes since this fork have been about improving code quality making it a lot easier to maintain.
