### ISSUE TITLE
Submit this to Ubuntu Team for a possibility that this replaces Ambiance in 18.04 LTS?

### ISSUE THREAD

**Issue by dominichayesferen** [marc0tjevp/United-GTK#2]
What it says in the title... I'm not sure personally of where the theme contest will be held at, though, but it'd be MORE THAN AWESOME to see your theme be the theme of Ubuntu 18.04 out of the box... :)

**Comment by marc0tjevp** [comment]
Thanks for the support, Glad you like it. If they ever run a contest I'd like to participate for sure, but I don't think the theme is polished enough as for now.

**Comment by dominichayesferen** [comment]
@marc0tjevp The contest is OPEN
https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/16?_ga=2.147423294.804694054.1510434516-1860524007.1506625146

**Comment by dominichayesferen** [comment]
Welp. I guess that's it.
